name: Publish to d24n main

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
	  ssh-private-key: ${{ secrets.D24N_DEPLOY_PRIVATE_KEY }}
      - name: clone d24n.github.io
        run:  git clone git@github.com:d24n/d24n.github.io.git
      - name: overwrite d24n.github.io contents
        run:  cp -r d24n-unstatic/docs/* d24n.github.io/
      - name: republish
        run: |
	  cd d24n.github.io
	  git add .
	  git commit -m "Auto-publishing changes pushed to d24n-unstatic (github action)"
          git push



   